### ISSUE TITLE
Mermaid breaks when a variable ends in 'v'

### ISSUE THREAD

**Issue by FrenchBen** [JozoVilcek/gitbook-plugin-mermaid#19]
## Steps to reproduce

Create a simple graph on a README.md (can be any .md)

```
{% mermaid %}
graph TD;

  A(First Box)
  B(Second Box)
  A-->B
{% endmermaid %}
```

Now change any variable to end with 'v' and you'll get errors:

```
{% mermaid %}
graph TD;

  Av(First Box)
  B(Second Box)
  Av-->B
{% endmermaid %}
```

errors:

```
phantom stdout: TypeError: 'undefined' is not an object (evaluating 'w[0]')
phantom stdout:  .../node_modules/gitbook-plugin-mermaid/convert/assets/mermaid.min.js:11
phantom stdout:   phantomjs://webpage.evaluate():3

Template render error: (/README.md)
  TypeError: Cannot read property 'replace' of null
```

**Comment by FrenchBen** [comment]
This has been fixed in the latest mermaid plugin - What can I do to help get this fixed here too?

http://knsv.github.io/mermaid/live_editor/#/edit/Z3JhcGggVEQ7CgogIEF2KEZpcnN0IEJveCkKICBCKFNlY29uZCBCb3gpCiAgQXYtLT5C

**Comment by JozoVilcek** [comment]
I have upgraded to mermaid v0.5.6. You ca try out new version of the plugin.

**Comment by FrenchBen** [comment]
Thanks @JozoVilcek - That fixed it :+1:
