### ISSUE TITLE
Include diagrams in generated pdf

### ISSUE THREAD

**Issue by knsv** [JozoVilcek/gitbook-plugin-mermaid#3]
Hi!

This is a good feature and its cool to see mermaid diagrams in generated books!

Would it be possible to have the generated diagrams to be included in a generated pdf or ePub? Or are there some obstacle for that? If  it is not pissble to use svgs perhaps one could extract the diagrams as pngs using the mermaid cli in the build step with some naming convention and include the pngs in the conversion to pdf/epub?

Thanks for this work!

**Comment by JozoVilcek** [comment]
Frankly, I did not ever try to generate pdf from gitbook :), nor I am aware of any preconditions required from plugins to be compatible. I will ask gitbook people and maybe give it a shot with svg.

Thanks!

**Comment by ciarant** [comment]
Hey all. Did you guys ever make any progress on this?

**Comment by JozoVilcek** [comment]
Sorry for the late response. I did some experiments at that time, but hit a bump. I was not able to generate same looking svg/png with phantomjs or mermaid cli. I recall it was something with arrow labels, D3 compatibility and hacks in css-es. I can not find an issue in mermaid now, so I might be confused :)

Anyway, this is still open and I was not able to make a significant progress yes. Sorry.

**Comment by knsv** [comment]
Maybe thing could work better now. There are configuration options for rendering svgs that works outside the browser. The options can be set before rendering like in the code snippet below.
- cloneCssStyles - With this option set mermaid copies the relevant css rules and includes them in the generated svg
- flowchart.htmlLabels - WIth this option the labels in the svg is rendered using html which gives better formatting possibilities, this will not work outside a browser though so it can be turned off.

```
var config = {
    cloneCssStyles: true,
    flowchart:{
        htmlLabels:false
    }
};
mermaid.initialize(config);
```

If you are up for it it might be time for a revisit. Also if there are other requirements on mermaid I will try to help.

**Comment by JozoVilcek** [comment]
I will try to resurrect my attempts asap and get back with results or questions. Thanks.

**Comment by JozoVilcek** [comment]
I have put together first iteration. Result is in branch [here](https://github.com/JozoVilcek/gitbook-plugin-mermaid/tree/server-side-diagrams). 

Basically it works, but e.g. labels on diagram links looks a bit ugly. They look the same even when I open [convert.html](https://github.com/JozoVilcek/gitbook-plugin-mermaid/blob/server-side-diagrams/convert/converter.html) in browser, so ... I am probably using mermaind in wrong way?

When used in gitbook, here are few things I noticed so far:
- inserted flow diagrams are not centered in view (sequence diagrams are centered)
- collision in chart IDs (and styles) when generating each diagram on the page separately

I can, later on, provide a working example.

**Comment by piranna** [comment]
I'm also interested on this, for my thesis, I could help testing if needed.

**Comment by JozoVilcek** [comment]
If anyone wants to give it a try ... Master version now generates svg from mermaid code and embed it into the gitbook when markdown gets processed. I have not tested it with pdf gitbook output.

**Comment by mariomelo** [comment]
Nice, I was just looking for that! :)

I'll update my book to the 0.05 version as soon as possible.

**Comment by knsv** [comment]
Excellent. I will try it out!

**Comment by mariomelo** [comment]
I think you misunderstood me @knsv. I'm also waiting for the new release. :)

Ps: I edited my previous answer to make it clearer

**Comment by JozoVilcek** [comment]
Version is not released yet. You have to try it from git master branch. Let me know if this is an issue.
Yould be great if you can provide feedback if this works with gitbook pdf output format.

P.S.: Plugin now requires gitbook engine 2.x.x

**Comment by piranna** [comment]
Master code can be able to generate the graphs and embed them inside PDF, but they are a little bit small and with the low resolution problems GitBook have with SVG rendering they get blurry and difficult to read. Since [Mermaid support some configuration](http://knsv.github.io/mermaid/flowchart.html#configuration-), shouldn't they be created with `width: 100%` by default? Where should I add this config?

**Comment by piranna** [comment]
According to [the code of Mermaid[(https://github.com/knsv/mermaid/blob/6f96b5dd1432d042c60d3a03f8fb67a6ee33e288/src/diagrams/flowchart/flowRenderer.js#L414-L431), I'm not sure if we should use `width` or `useMaxWidth`... seems the last one autoconfig both width and height to use maximus available space...

**Comment by JozoVilcek** [comment]
Can someone confirm diagrams are visible in `pdf` now? I have no luck to generate gitbook pdf on my ubuntu ... observing some `calibre` errors.

**Comment by piranna** [comment]
I'm having diagrams correctly shown on PDFs...

**Comment by JozoVilcek** [comment]
Great! Thank you @piranna
