### ISSUE TITLE
Which Gitbook Plugin?

### ISSUE THREAD

**Issue by SeaDude** [JozoVilcek/gitbook-plugin-mermaid#30]
Hello, 

There are [7 Mermaid GItbook plugins](https://plugins.gitbook.com/browse?q=mermaid). They mostly appear the same. Which one is the official, supported, current, Mermaid plugin? 

Thanks

**Comment by JozoVilcek** [comment]
Honestly, I do not know. This plugin is not maintained any more and supports only gitbook 2.x
