### ISSUE TITLE
Use directly phantomjs module instead of phantom

### ISSUE THREAD

**Issue by piranna** [JozoVilcek/gitbook-plugin-mermaid#5]
phantomjs module automatically installs PhantomJS so it's not needed to be installed externally, so it would help to make books more autocontained and generated by non-tech people just by doing `npm install`.

**Comment by piranna** [comment]
Also, phantomjs modules is more updated and maintained (one month versus 8 months of phantom) and used by 10x people of phantom...

**Comment by piranna** [comment]
This has been fixed on pull-request https://github.com/JozoVilcek/gitbook-plugin-mermaid/pull/11. `phantom` module is still required because `phantomjs` only download the binary, but I've managed instead to ask him the location of the binary instead of depend only on a globally installed one.

**Comment by JozoVilcek** [comment]
I have merged your pull request. Thanks for this. I like the solution

**Comment by piranna** [comment]
You are welcome :-) Could this be possible to be published on npm, too?

**Comment by JozoVilcek** [comment]
Sure, I will publish as soon as I resolve #7

**Comment by piranna** [comment]
Ok, agree :+1:

**Comment by JozoVilcek** [comment]
Released

**Comment by piranna** [comment]
Cool! :-D
