### ISSUE TITLE
Load mermaid graphs from external files

### ISSUE THREAD

**Issue by piranna** [JozoVilcek/gitbook-plugin-mermaid#7]
Allow to give an url as argument of the block to load the graph from a file instead of need to embed it in the book content, similar to the url attribute of the html script tag.

**Comment by JozoVilcek** [comment]
Great!

**Comment by JozoVilcek** [comment]
I am having trouble to test it out. I have placed a file with diagram right next to the gitbook page and trying to load block 

```
{% mermaid src="diagram.mermaid" %}
{% endmermaid %}
```

Gitbook is complaining

```
Template render error: (/home/jvilcek/projects/gitbook-example/src/book/chapter-1/diagrams.md)
  Error: ENOENT, no such file or directory 'chapter-1/diagram.mermaid' (In file 'chapter-1/diagrams.md')
```

**Comment by piranna** [comment]
Strange, it's working for me... :-/ Maybe the path where you are generating it?

**Comment by piranna** [comment]
File content is read at https://github.com/JozoVilcek/gitbook-plugin-mermaid/blob/5ec22f91f731627c9686df6a8226a9f5c1b6a56c/index.js#L22-L23, maybe the path should be converted to an absolute one?

**Comment by JozoVilcek** [comment]
This works for me 81cf5ed3beffae6a82f07c83f0c28e1df01109f4
